# TypeProf 0.31.1

# lib/mui/config.rb
module Mui
  class Config
    def options: -> Hash[:colorscheme | :expandtab | :leader | :reselect_after_indent | :shiftwidth | :syntax | :tabstop | :timeoutlen | :use_yjit, Integer | String | bool]
    def plugins: -> []
    def keymaps: -> Hash[untyped, Hash[untyped, untyped]]
    def commands: -> Hash[untyped, untyped]
    def autocmds: -> Hash[untyped, []]
    def initialize: -> void
    def set: (untyped, untyped) -> untyped
    def get: (untyped) -> (Integer | String | bool)
    def load_file: (untyped) -> nil
    def use_plugin: (untyped, ?nil) -> []
    def add_keymap: (untyped, untyped, untyped) -> untyped
    def add_command: (untyped, untyped) -> untyped
    def add_autocmd: (untyped, untyped, untyped) -> []
  end
end
