# TypeProf 0.31.1

# lib/mui/error.rb
module Mui
  class Mui::Error < StandardError
  end
  class Mui::MethodNotOverriddenError < Mui::Error
    def initialize: (untyped) -> void
  end
  class Mui::PluginError < Mui::Error
  end
  class Mui::PluginNotFoundError < Mui::PluginError
    def initialize: (untyped) -> void
  end
  class Mui::UnknownCommandError < Mui::Error
    def initialize: (untyped) -> void
  end
end
