# TypeProf 0.31.1

# lib/mui/syntax/lexers/ruby_lexer.rb
module Mui
  module Mui::Syntax
    module Mui::Syntax::Lexers
      class Mui::Syntax::Lexers::RubyLexer # failed to identify its superclass
        Mui::Syntax::Lexers::RubyLexer::KEYWORDS: Array[String]
        Mui::Syntax::Lexers::RubyLexer::COMPILED_PATTERNS: Array[[:comment, Regexp] | [:constant, Regexp] | [:function_definition, Regexp] | [:global_variable, Regexp] | [:identifier, Regexp] | [:instance_variable, Regexp] | [:keyword, Regexp] | [:method_call, Regexp] | [:number, Regexp] | [:operator, Regexp] | [:string, Regexp] | [:symbol, Regexp]]
        Mui::Syntax::Lexers::RubyLexer::BLOCK_COMMENT_END: Regexp
        Mui::Syntax::Lexers::RubyLexer::BLOCK_COMMENT_START: Regexp
        def compiled_patterns: -> Array[[:comment, Regexp] | [:constant, Regexp] | [:function_definition, Regexp] | [:global_variable, Regexp] | [:identifier, Regexp] | [:instance_variable, Regexp] | [:keyword, Regexp] | [:method_call, Regexp] | [:number, Regexp] | [:operator, Regexp] | [:string, Regexp] | [:symbol, Regexp]]
        def handle_multiline_state: (untyped, untyped, untyped) -> ([nil, :block_comment, untyped] | [nil, nil, untyped] | [untyped, nil, untyped])
        def check_multiline_start: (untyped, untyped) -> ([:block_comment, untyped, untyped] | [nil, nil, untyped])
      end
    end
  end
end
