# TypeProf 0.31.1

# lib/mui/key_handler/operators/paste_operator.rb
module Mui
  module Mui::KeyHandler
    module Mui::KeyHandler::Operators
      class Mui::KeyHandler::Operators::PasteOperator # failed to identify its superclass
        def paste_after: (?pending_register: nil) -> :done
        def paste_before: (?pending_register: nil) -> :done
        def handle_pending: (untyped, ?pending_register: nil) -> :cancel
        def paste_line_after: (?name: nil) -> untyped
        def paste_line_before: (?name: nil) -> untyped
        def paste_char_after: (?name: nil) -> untyped
        def paste_char_before: (?name: nil) -> untyped
        def paste_multiline_char: (untyped, untyped, Integer) -> untyped
      end
    end
  end
end
